services:
  db:
    image: mysql:8.0
    container_name: stockwars_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2007
      - MYSQL_DATABASE=stockwars

  cache:
    image: redis:alpine
    container_name: stockwars_redis
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:v2.50.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: stockwars_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
